### ISSUE TITLE
Broken links in vGPU.md

### ISSUE THREAD

**Issue by leggerf** [Open-ForBC/OpenForBC#3]
https://github.com/Open-ForBC/OpenForBC/blob/main/docs/nvidia/vGPU.md#configuring-mig-backed-vgpus
https://github.com/Open-ForBC/OpenForBC/blob/main/docs/nvidia/mig.md
https://github.com/Open-ForBC/OpenForBC/blob/main/docs/nvidia/vGPU.md#time-sliced-vgpu-scheduling-bahevior
https://github.com/Open-ForBC/OpenForBC/blob/main/docs/nvidia/mig.md#mig-gpu-instance

**Comment by leggerf** [comment]
ok, let's leave it open until vGPU doc is fixed, so that I remember to check it

**Comment by iH8c0ff33** [comment]
This should be fixed now.

**Comment by leggerf** [comment]
link is not existing because Daniele still needs to understand how it works

**Comment by leggerf** [comment]
fixed to nVIdia link: https://docs.nvidia.com/grid/13.0/grid-vgpu-user-guide/index.html#changing-vgpu-scheduling-policy
